# Changes here will be overwritten by Copier.
_commit: 1.11.0
_src_path: gh:pawamoy/copier-uv
author_email: lespana@mcw.edu
author_fullname: Lezlie Espana
author_username: l-espana
copyright_date: '2025'
copyright_holder: MCW Meier Lab
copyright_holder_email: lespana@mcw.edu
copyright_license: MIT
insiders: false
project_description: Python tools for diffusion tractography visualization
project_name: pyTractoViz
python_package_command_line_name: pytractoviz
python_package_distribution_name: pytractoviz
python_package_import_name: pytractoviz
repository_name: pytractoviz
repository_namespace: mcw-meier-lab
repository_provider: github.com

